# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-devel
warnings_are_errors: false
bioc_use_devel: true
r_build_args: --keep-empty-dirs --no-resave-data
r_check_args: --timings

